window.COVERAGEFIT_CONFIG = {
  slug:"home",
  toolId:"review-tool",
  reportPath:"/home/report/",
  defaultName:"Homeowner",
  finalButtonLabel:"Build My Protection Snapshot",
  warningPoint:-12,
  thresholds:{strong:85,review:68},
  priority:{
    strong:"Confirm your current policy details with a licensed producer.",
    review:"Schedule a coverage review to examine the areas identified in your report.",
    weak:"Prioritize a licensed review of the higher-concern areas identified in your report."
  },
  results:{
    strong:{badge:"Strong Starting Point",badgeClass:"good",title:"Your answers suggest a stronger protection starting point.",copy:"Several important areas appear understood or addressed. Your personalized report will show what looks strong and what is still worth confirming in the actual policy."},
    review:{badge:"Review Recommended",badgeClass:"medium",title:"Your answers identify areas worth a closer look.",copy:"Your score is not a coverage determination. It is a conversation starter designed to help you focus a licensed review on the areas most likely to matter."},
    weak:{badge:"Higher Review Priority",badgeClass:"weak",title:"Your answers show several areas that deserve attention.",copy:"Your personalized report will organize the highest-priority topics so you can have a more productive conversation before a claim forces the issue."}
  },
  questions:[
    {key:"dwelling",category:"Rebuilding",weight:18,title:"If your home had to be rebuilt after a total loss, how confident are you that the rebuilding amount reflects today's construction costs?",help:"Why we're asking: rebuilding cost and market value are often very different. Many homeowners review this after renovations or rising construction costs.",answers:[
      {label:"Very confident",sub:"It was recently reviewed using current rebuilding information.",points:0,tag:"Dwelling Coverage",insight:"Your dwelling limit was reviewed using current rebuilding information.",question:"When was my rebuilding estimate last updated, and what assumptions were used?"},
      {label:"Somewhat confident",sub:"It has not been reviewed recently.",points:-8,tag:"Dwelling Coverage",insight:"Your rebuilding amount may not have been reviewed recently.",question:"Can we update the replacement-cost estimate using current construction information?"},
      {label:"Not sure",sub:"I do not know how the amount was calculated.",points:-18,tag:"Dwelling Coverage",insight:"You are unsure how the dwelling limit was calculated.",question:"How was my dwelling limit calculated, and would it realistically rebuild the home today?"}]},
    {key:"extendedReplacement",category:"Rebuilding",weight:12,title:"If rebuilding costs unexpectedly increased after a major disaster, do you know whether your policy provides additional protection above your dwelling limit?",help:"Why we're asking: construction costs can rise quickly after widespread disasters. Some policies include additional rebuilding protection above the dwelling limit.",answers:[
      {label:"Yes",sub:"I believe additional rebuilding protection is included.",points:0,tag:"Extended Replacement",insight:"You believe extended rebuilding protection is included.",question:"What percentage of extended replacement cost does my policy provide?"},
      {label:"No",sub:"I do not believe it is included.",points:-14,tag:"Extended Replacement",insight:"Your policy may not include additional rebuilding protection above the dwelling limit.",question:"What happens if rebuilding costs exceed my dwelling limit after a widespread disaster?"},
      {label:"Not sure",sub:"I have never checked.",points:-12,tag:"Extended Replacement",insight:"You have not confirmed whether extended rebuilding protection is included.",question:"Does my policy include extended replacement cost, and what conditions apply?"}]},
    {key:"ordinanceLaw",category:"Rebuilding",weight:10,title:"If your home had to be rebuilt to today's building codes, are you confident your policy helps cover those additional costs?",help:"Why we're asking: rebuilding may require electrical, plumbing, structural, or safety upgrades that were not part of the original home.",answers:[
      {label:"Yes",sub:"I know the limit or percentage.",points:0,tag:"Ordinance and Law",insight:"You know your ordinance or law limit.",question:"Is my ordinance or law limit still appropriate for my home’s age and local building codes?"},
      {label:"No",sub:"I do not believe it is included.",points:-12,tag:"Ordinance and Law",insight:"Code-upgrade costs may deserve review.",question:"How would required code upgrades be paid after a covered rebuilding loss?"},
      {label:"Not sure",sub:"I have never reviewed it.",points:-10,tag:"Ordinance and Law",insight:"You have not confirmed protection for required code upgrades.",question:"What ordinance or law coverage is included in my policy?"}]},
    {key:"water",category:"Water",weight:14,title:"If a pipe burst or water escaped inside your home tomorrow, how confident are you that you understand what your policy would and would not cover?",help:"Why we're asking: water losses can involve separate deductibles, backup limits, seepage exclusions, and mitigation requirements that are easy to overlook.",answers:[
      {label:"Very well",sub:"I understand the deductible and major limitations.",points:0,tag:"Water Damage",insight:"You understand your main water-damage terms.",question:"Are there any separate water deductibles, exclusions, or mitigation requirements I should know about?"},
      {label:"Somewhat",sub:"I know the basics but not the details.",points:-8,tag:"Water Damage",insight:"Some water-damage terms may still be unclear.",question:"Can we review the types of water loss my policy covers, limits, and deductibles?"},
      {label:"Not sure",sub:"I do not know how the policy handles water losses.",points:-16,tag:"Water Damage",insight:"Your policy’s treatment of water losses is unclear.",question:"How does my policy handle sudden water damage, backup, seepage, and hidden leaks?"}]},
    {key:"deductible",category:"Financial Readiness",weight:10,title:"If you had a covered claim tomorrow, could you comfortably pay your deductible without creating financial stress?",help:"Why we're asking: the deductible is the amount you may need to access quickly before repairs or recovery can move forward.",answers:[
      {label:"Yes",sub:"I have funds available for it.",points:0,tag:"Deductible",insight:"Your current deductible appears financially manageable.",question:"Are any separate deductibles higher than my standard home deductible?"},
      {label:"It would be difficult",sub:"I could pay it, but it would strain my finances.",points:-8,tag:"Deductible",insight:"Your deductible could create financial strain during a claim.",question:"Would a different deductible structure better balance premium and out-of-pocket risk?"},
      {label:"No",sub:"I would struggle to cover it.",points:-14,tag:"Deductible",insight:"Your deductible may be difficult to fund after a loss.",question:"What deductible options could make a claim more financially manageable?"}]},
    {key:"liability",category:"Liability",weight:14,title:"If someone were seriously injured on your property, how confident are you that your liability protection reflects your current lifestyle?",help:"Why we're asking: serious injuries and lawsuits can affect savings, income, and assets, not just the property itself.",answers:[
      {label:"$500,000 or higher",sub:"A stronger baseline for many households, depending on exposure.",points:0,tag:"Liability",insight:"Your stated liability limit is a stronger starting point.",question:"Does my liability limit match my assets, income, household exposures, and risk tolerance?"},
      {label:"$300,000",sub:"May be reasonable but should be reviewed with the overall exposure.",points:-6,tag:"Liability",insight:"Your liability limit may be worth comparing with your broader exposure.",question:"Would increasing liability protection materially improve my overall risk position?"},
      {label:"$100,000 or less",sub:"Potentially low for many homeowners.",points:-18,tag:"Liability",insight:"Your stated liability limit may be low relative to many homeowner exposures.",question:"What could happen financially if a serious liability claim exceeds my policy limit?"},
      {label:"Not sure",sub:"I do not know my current limit.",points:-14,tag:"Liability",insight:"You do not know your current personal liability limit.",question:"What is my current personal liability limit and what exposures should it address?"}]},
    {key:"personalProperty",category:"Property",weight:8,title:"If your belongings were damaged, destroyed, or stolen, how confident are you that your policy would replace what matters most?",help:"Why we're asking: belongings may be covered differently from the home itself, and items such as jewelry, art, electronics, or collections may have special limits.",answers:[
      {label:"Very confident",sub:"I have reviewed my limits and valuables.",points:0,tag:"Personal Property",insight:"You have reviewed your belongings and valuable items.",question:"Are my belongings covered at replacement cost, and are valuable items properly scheduled?"},
      {label:"Somewhat confident",sub:"I have not reviewed everything recently.",points:-7,tag:"Personal Property",insight:"Your personal property protection may need a refresh.",question:"Do my limits and special sublimits still match what I own today?"},
      {label:"Not sure",sub:"I do not know the limit or settlement method.",points:-14,tag:"Personal Property",insight:"Your personal property limit and settlement method are unclear.",question:"What personal property limit and loss-settlement method does my policy use?"}]},
    {key:"lossOfUse",category:"Recovery",weight:8,title:"If your home became unlivable after a covered loss, do you know how long your policy could help support temporary housing and added living costs?",help:"Why we're asking: recovery can take months. The available amount or time period can shape where your household lives and how smoothly you recover.",answers:[
      {label:"Yes",sub:"I know the limit or duration.",points:0,tag:"Additional Living Expense",insight:"You understand your temporary living-expense protection.",question:"How long could my current limit realistically support my household after a major loss?"},
      {label:"No",sub:"I do not believe I have reviewed it.",points:-10,tag:"Additional Living Expense",insight:"Your temporary living-expense protection has not been reviewed.",question:"What limit or time period applies if my home becomes uninhabitable?"},
      {label:"Not sure",sub:"I have never checked.",points:-10,tag:"Additional Living Expense",insight:"You are unsure how long the policy could support temporary housing.",question:"How much additional living expense coverage do I have and what costs qualify?"}]},
    {key:"umbrella",category:"Liability",weight:6,title:"If a major lawsuit exceeded your home or auto liability limits, do you know whether you have additional liability protection?",help:"Why we're asking: larger liability claims may extend beyond one policy. An umbrella can add another layer when it is properly coordinated.",answers:[
      {label:"Yes",sub:"I already carry an umbrella.",points:0,tag:"Umbrella",insight:"You already carry additional umbrella liability protection.",question:"Are all of my underlying policies and exposures properly coordinated with the umbrella?"},
      {label:"No",sub:"I do not currently carry one.",points:-6,tag:"Umbrella",insight:"You do not currently carry umbrella liability protection.",question:"Based on my assets, income, drivers, rentals, and activities, should I consider an umbrella?"},
      {label:"Not sure whether I need one",sub:"I have not reviewed my overall liability exposure.",points:-8,tag:"Umbrella",insight:"Your need for umbrella liability has not been evaluated.",question:"What personal exposures could make an umbrella appropriate for my household?"}]},
    {key:"lifeEvents",category:"Life Changes",weight:8,title:"Have there been any important life changes since your insurance was last reviewed?",help:"Why we're asking: protection can fall out of date when the home, household, property use, or financial responsibilities change.",answers:[
      {label:"No major changes",sub:"My household and property use are generally unchanged.",points:0,tag:"Life Changes",insight:"No major recent life changes were identified.",question:"Are there any smaller household or property changes that should still be documented?"},
      {label:"Yes, and my policies were reviewed",sub:"I discussed the changes with a licensed professional.",points:0,tag:"Life Changes",insight:"Recent changes were reviewed with a licensed professional.",question:"Were all relevant home, auto, life, umbrella, and business policies updated?"},
      {label:"Yes, but my policies were not reviewed",sub:"My household, property, or activities changed.",points:-14,tag:"Life Changes",insight:"A recent life or property change may not yet be reflected in your insurance.",question:"How should my recent changes affect my home and related insurance protection?"}]}
  ]
};
